

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pvng2003@gmail.com
spring.mail.password=hvxfouuccgemalwi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#cấu hình 
server.port= 8080
spring.mvc.view.prefix= /WEB-INF/views/
spring.mvc.view.suffix= .jsp

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Website_Lamborghini;encrypt=true;trustServerCertificate=true;
#kiểm tra tài khoản và mật khẩu chính xác
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# SQLServer2012Dialect dẫn chạy ổn nên cứ để nếu lỗi ko kết nối hãy đổi l
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect
