
#cấu hình 


spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Website_Lamborghini;encrypt=true;trustServerCertificate=true;
#kiểm tra tài khoản và mật khẩu chính xác
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
# SQLServer2012Dialect dẫn chạy ổn nên cứ để nếu lỗi ko kết nối hãy đổi l
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2012Dialect



